### ISSUE TITLE
Also does not compile with 5.24.0

### ISSUE THREAD

**Issue by dmcbride** [Corion/Coro#4]
This is a much bigger issue than the trivial one with 5.22.1:

```$ make
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"6.49\" -DXS_VERSION=\"6.49\" -fPIC "-I/opt/myperl/5.24.0/lib/5.24.0/x86_64-linux-thread-multi/CORE"  -DCORO_ASM -DCORO_STACKSIZE=16384 -DCORO_GUARDPAGES=4 -DCORO_USE_VALGRIND=1 -DCORO_JIT=1 State.c
In file included from /opt/myperl/5.24.0/lib/5.24.0/x86_64-linux-thread-multi/CORE/perl.h:5554:0,
                 from State.xs:12:
State.xs: In function ‘runops_trace’:
State.xs:1398:91: error: ‘struct block_sub’ has no member named ‘argarray’
                           PUSHs (CxHASARGS (cx) ? sv_2mortal (newRV_inc ((SV *)cx->blk_sub.argarray)) : &PL_sv_undef);
                                                                                           ^
/opt/myperl/5.24.0/lib/5.24.0/x86_64-linux-thread-multi/CORE/pp.h:451:28: note: in definition of macro ‘PUSHs’
 #define PUSHs(s) (*++sp = (s))
                            ^
State.xs:1398:51: note: in expansion of macro ‘sv_2mortal’
                           PUSHs (CxHASARGS (cx) ? sv_2mortal (newRV_inc ((SV *)cx->blk_sub.argarray)) : &PL_sv_undef);
                                                   ^
/opt/myperl/5.24.0/lib/5.24.0/x86_64-linux-thread-multi/CORE/sv.h:1970:23: note: in expansion of macro ‘newRV’
 #define newRV_inc(sv) newRV(sv)
                       ^
State.xs:1398:63: note: in expansion of macro ‘newRV_inc’
                           PUSHs (CxHASARGS (cx) ? sv_2mortal (newRV_inc ((SV *)cx->blk_sub.argarray)) : &PL_sv_undef);
                                                               ^
State.xs: In function ‘boot_Coro__State’:
State.xs:3604:81: error: assignment of member ‘svt_get’ in read-only object
         orig_sigelem_get = PL_vtbl_sigelem.svt_get;   PL_vtbl_sigelem.svt_get   = coro_sigelem_get;
                                                                                 ^
State.xs:3605:81: error: assignment of member ‘svt_set’ in read-only object
         orig_sigelem_set = PL_vtbl_sigelem.svt_set;   PL_vtbl_sigelem.svt_set   = coro_sigelem_set;
                                                                                 ^
State.xs:3606:81: error: assignment of member ‘svt_clear’ in read-only object
         orig_sigelem_clr = PL_vtbl_sigelem.svt_clear; PL_vtbl_sigelem.svt_clear = coro_sigelem_clr;
                                                                                 ^
distcc[28203] ERROR: compile State.c on localhost failed
Makefile:405: recipe for target 'State.o' failed
make: *** [State.o] Error 1
```
